name: CI
run-name: Results for ${{ github.sha }}
on: [push]
jobs:
  Run-Pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
      - name: Setup Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.11"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Perform Analysis
        run: |
          python -m pytest tests
  Run-Mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
      - name: Setup Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.11"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy
      - name: Perform Analysis
        run: |
          python -m mypy --strict .
